[DEFAULT]
# WPS OpenAPI 配置
# 请替换为您自己的应用 AK/SK
ACCESS_KEY = AK20260104YULVBI
SECRET_KEY = 056683a1563b1a7ac8e30ff05c345c23

# API 域名
DOMAIN = https://openapi.wps.cn

# 默认使用的 Drive ID (运行 setup 命令可生成新的)
# 这里的 ID 是 Demo 中的示例 ID
DEFAULT_DRIVE_ID = 4k78rOe

# 默认父目录 ID (0 表示根目录)
DEFAULT_PARENT_ID = 0

